(async () => {
    const TEST_ID = "VC139";
    const VARIANT_ID = "V1";
    function logInfo(message) {
        console.log(
            `%cAcadia%c${TEST_ID}-${VARIANT_ID}`,
            "color:white;background:rgb(0,0,57);font-weight:700;padding:2px 4px;border-radius:2px;",
            "margin-left:8px;color:white;background:rgb(0,57,57);font-weight:700;padding:2px 4px;border-radius:2px;",
            message,
        );
    }

    logInfo("fired");

    const TEST_CONFIG = {
        page_initials: "AB-VC139",
        test_variation: 1,
        test_version: 0.0002,
    };

    const { page_initials, test_variation, test_version } = TEST_CONFIG;

    function q(s, o) {
        return document.querySelector(s);
    }

    async function waitForElementAsync(predicate, timeout = 20000, frequency = 150) {
        const startTime = Date.now();

        return new Promise((resolve, reject) => {
            if (typeof predicate === "function" && predicate()) {
                return resolve(true);
            }

            const interval = setInterval(() => {
                const elapsed = Date.now() - startTime;

                if (elapsed >= timeout) {
                    clearInterval(interval);
                    return reject(new Error(`Timeout of ${timeout}ms reached while waiting for condition: ${predicate.toString()}`));
                }

                if (typeof predicate === "function" && predicate()) {
                    clearInterval(interval);
                    return resolve(true);
                }
            }, frequency);
        });
    }

    function injectStyles() {
        const style = document.createElement("style");
        style.id = `${page_initials}-styles`;
        style.textContent = `
            .AB-VC139 .global-sale-message.global-sale-message--autogenerated-msg {
                margin-top: 10px;
                padding: 5px 19px 5px 10px;
                background-color: #f0e1d7 !important;
            }
            .AB-VC139 .global-sale-message__msg {
                font-family: Lato;
                font-weight: 600;
                font-size: 14px;
                line-height: 100%;
                letter-spacing: 0px;
                color: #333333 !important;
                text-transform: lowercase;
            }
            .AB-VC139 .global-sale-message__msg  span {
                color: #333333 !important;
                text-transform: uppercase;
            }
            .AB-VC139.template-product .global-sale-message.global-sale-message--autogenerated-msg {
                margin-top: 0;
            }
            .AB-VC139.template-product .global-sale-message__msg {
                font-family: Lato;
                font-weight: 600 !important;
                font-size: 14px !important;
                line-height: 100% !important;
                letter-spacing: 0px !important;
                color: #333333 !important;
                text-transform: lowercase !important;
            }

        `;
        document.head.appendChild(style);
    }

    function init() {
        if (window[page_initials]) return;

        injectStyles();
        q("body").classList.add(page_initials, `${page_initials}--v${test_variation}`, `${page_initials}--version:${test_version}`);
        window[page_initials] = true;
    }

    function checkForItems() {
        return !!q(`body:not(.${page_initials}):not(.${page_initials}--v${test_variation})`);
    }

    await waitForElementAsync(checkForItems);
    init();
})();
