const mostPurchasedItems = [
    {
        id: "6959",
        name: 'Tempo 60" Display Laminated Loop Fabric',
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/wide-loop\/tempo-60-display-laminated-loop-fabric",
        sku: "DG-TEMPO",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/t\/e\/tempo3_2.jpg",
        price: "$45.45",
    },
    {
        id: "6863",
        name: "VELCRO\u00ae Brand Adhesive Backed Hook and Loop Fasteners",
        url: "https:\/\/www.hookandloop.com\/brands\/velcro\/peel-and-stick",
        sku: "VADHESIVE-161885",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/p\/s\/ps_rolls-velcro_black_acrylic_release_liner_2.jpg",
        price: "$33.75-$202.00",
    },
    {
        id: "6753",
        name: "DuraGrip Brand Display Loop",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/wide-loop\/display-loop",
        sku: "DWL-170783REGAL63",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/w\/i\/wide_loop-electric_blue_regal_detail_2.jpg",
        price: "$49.15",
    },
    {
        id: "6751",
        name: "DuraGrip Brand Wide Loop",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/wide-loop\/duragrip-brand-wide-loop",
        sku: "DWL-170783REGAL60",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/c\/o\/coyote_brown_wide_loop2.jpg",
        price: "$38.07",
    },
    {
        id: "6747",
        name: "VELCRO\u00ae Brand ONE-WRAP\u00ae Fastener",
        url: "https:\/\/www.hookandloop.com\/brands\/velcro\/double-sided-cable-ties",
        sku: "VOWF-170",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/o\/n\/one-wrap-black_7_1.jpg",
        price: "$27.50-$193.25",
    },
    {
        id: "6307",
        name: "VELCRO\u00ae Brand ONE-WRAP\u00ae Cable Ties",
        url: "https:\/\/www.hookandloop.com\/brands\/velcro\/cable-ties",
        sku: "VOWF-1707",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/b\/l\/black_cable_ties_4_1_1.jpg",
        price: "$0.50-$2.47",
    },
    {
        id: "6299",
        name: "DuraGrip\u00ae Brand Polypropylene Webbing",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/webbing",
        sku: "DW-DG20RDWEBB",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/r\/e\/red_7_1_.jpg",
        price: "$25.00-$118.00",
    },
    {
        id: "6298",
        name: "VELCRO\u00ae Brand Wide Sheets and Loop",
        url: "https:\/\/www.hookandloop.com\/brands\/velcro\/wide-loop",
        sku: "VW-195872",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/r\/o\/rolls-wideloop_reshoot_1.jpg",
        price: "$14.55-$37.25",
    },
    {
        id: "6288",
        name: "DuraGrip\u00ae Brand Adhesive Backed Hook and Loop Fasteners",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/peel-and-stick",
        sku: "Adhesive-DG-Brand-peel-and-stick",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/p\/s\/ps_rolls-duragrip_white_rubber_liner_1.jpg",
        price: "$14.75-$146.75",
    },
    {
        id: "6286",
        name: "DuraGrip\u00ae Brand Hook and Loop Coins",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/coins",
        sku: "DC-DGC78WHL",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/r\/o\/rolls-duragrip_dgc34blh_1.png",
        price: "$33.75-$67.50",
    },
    {
        id: "6285",
        name: "VELCRO\u00ae Brand VELCOIN\u00ae Hook and Loop Fasteners",
        url: "https:\/\/www.hookandloop.com\/brands\/velcro\/coins",
        sku: "VVC-192342",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/r\/o\/rolls-velcro_dots_192245_angled_1.png",
        price: "$60.00-$117.50",
    },
    {
        id: "6284",
        name: "VELCRO\u00ae Brand Sew On Hook and Loop Fasteners",
        url: "https:\/\/www.hookandloop.com\/brands\/velcro\/sew-on",
        sku: "VSEWON-181214",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/r\/o\/rolls-velcro_190431.jpg",
        price: "$18.00-$271.75",
    },
    {
        id: "6361",
        name: "DuraGrip Brand Medical Channel Loop Fasteners",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/duragrip-brand-medical-channel-loop-fasteners",
        sku: "DG10BLCL-CON",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/d\/g\/dg10channel_copy.png",
        price: "$42.50-$106.25",
    },
    {
        id: "6360",
        name: "DuraGrip Brand Adhesive Backed Fire Retardant Hook and Loop",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/specialty\/sew-on-fire-retardant-hook-and-loop",
        sku: "DFR-DG10BLHFRA",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/p\/s\/ps_rolls-duragrip_black_rubber_shear_1.jpg",
        price: "$50.88-$126.23",
    },
    {
        id: "6341",
        name: "DuraGrip Brand Back to Back Hook and Loop",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/specialty\/back-to-back-hook-and-loop",
        sku: "CON-DLTL-DG10BLL",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/r\/o\/rolls-hook_to_hook_detail_macro_1.jpg",
        price: "$46.75-$93.75",
    },
    {
        id: "6310",
        name: "DuraGrip Brand Low-Profile Hook",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/specialty\/duragrip-brand-low-profile-hook",
        sku: "DG-LOW-PROFILE",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/d\/g\/dg10h3_copy_3.png",
        price: "$17.50-$102.00",
    },
    {
        id: "6309",
        name: "DuraGrip Brand Total Hook Fastener",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/specialty\/duragrip-brand-total-hook-fastener",
        sku: "DTH-DG15BLTH",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/r\/o\/rolls-total_hook_detail_1_1_.jpg",
        price: "$23.75-$57.50",
    },
    {
        id: "6308",
        name: "DuraGrip Brand Rings",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/ring",
        sku: "DGRLHE2",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/2\/_\/2_inch_black_ring_pair_bn401-0200.jpg",
        price: "$70.00",
    },
    {
        id: "6303",
        name: "DuraGrip Brand Stretch Loop",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/stretch-loop",
        sku: "DSTR-DG58BLS",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/s\/t\/stretch_loop_1_.jpg",
        price: "$70.00-$189.20",
    },
    {
        id: "6293",
        name: "DuraGrip\u00ae Brand Electrically Conductive Hook and Loop",
        url: "https:\/\/www.hookandloop.com\/brands\/duragrip\/specialty\/electrically-conductive-hook-and-loop",
        sku: "DEC-DG20ELCL",
        image: "https:\/\/www.hookandloop.com\/media\/catalog\/product\/cache\/74c1057f7991b4edb2bc7bdaa94de933\/d\/g\/dgelcl_2.jpg",
        price: "$54.12-$87.57",
    },
];
