const res = {
    pagination: {
        totalResults: 258,
        begin: 1,
        end: 4,
        currentPage: 1,
        totalPages: 65,
        previousPage: 0,
        nextPage: 2,
        perPage: 4,
        defaultPerPage: 45,
    },
    sorting: {
        options: [
            {
                field: "relevance",
                direction: "desc",
                label: "Best Match",
            },
            {
                field: "ga_unique_purchases",
                direction: "desc",
                label: "Best Selling",
            },
            {
                field: "datecreated",
                direction: "desc",
                label: "Newest",
            },
            {
                field: "productname",
                direction: "asc",
                label: "Name: A to Z",
            },
            {
                field: "productname",
                direction: "desc",
                label: "Name: Z to A",
            },
            {
                field: "ss_price",
                direction: "asc",
                label: "Price: Low to High",
            },
            {
                field: "ss_price",
                direction: "desc",
                label: "Price: High to Low",
            },
        ],
    },
    resultLayout: "grid",
    results: [
        {
            allcategories: [
                "Discounted  Accessories",
                "ALS",
                "ALS  Accessories",
                "Physio-Control  Manual  Defibrillator  Accessories",
                "LIFEPAK  15  Accessories",
                "Operating  Instructions/Service  Manuals/Videos",
                "All  Products  excluding  aha  zoll  accessories  training  manikins",
                "allproductsexceptexcluded",
                "allproductsexceptexcludedNOAEDS",
                "allproductsexceptexcluded-no-zoll",
            ],
            brand: "Physio-Control",
            catalogid: "1582",
            categoryid: ["212", "513", "1599", "1602", "1634", "1636"],
            categoryname: [
                "Discounted  Accessories",
                "Operating  Instructions/Service  Manuals/Videos",
                "All  Products  excluding  aha  zoll  accessories  training  manikins",
                "allproductsexceptexcluded",
                "allproductsexceptexcludedNOAEDS",
                "allproductsexceptexcluded-no-zoll",
            ],
            categorypaths:
                "Discounted  Accessories |ALS| ALS  &gt;  ALS  Accessories | ALS  &gt;  ALS  Accessories  &gt;  Physio-Control  Manual  Defibrillator  Accessories | ALS  &gt;  ALS  Accessories  &gt;  Physio-Control  Manual  Defibrillator  Accessories  &gt;  LIFEPAK  15  Accessories | ALS  &gt;  ALS  Accessories  &gt;  Physio-Control  Manual  Defibrillator  Accessories  &gt;  LIFEPAK  15  Accessories  &gt;  Operating  Instructions/Service  Manuals/Videos | All  Products  excluding  aha  zoll  accessories  training  manikins |allproductsexceptexcluded|allproductsexceptexcludedNOAEDS|allproductsexceptexcluded-no-zoll",
            id: "e90e0659a2a701799ae463a8080f81ab",
            imageUrl: "//www.aedsuperstore.com/assets/images/thumbnails/26500-002408_thumbnail.jpg",
            intellisuggestData: "eJwATQCy_3pzcno0YQBmOWFhNjFlOC05MGYwLTRiNzQtYTE4NC04N2RhMzg0MThiNWIAZGVmaWIAMjY1MDAtMDAyNDA4ADEAMQAwADI1OABncmlkAwAgAhLk",
            intellisuggestSignature: "75b69839ae45492b9eb642d9cefd74f48b98b03264bd311b7deeaebe4a33059a",
            msrp: "72",
            name: "Physio-Control LIFEPAK 15 Monitor/Defibrillator Operating Instructions",
            price: "72",
            pricelevel1: "72",
            pricelevel10: "0",
            pricelevel2: "0",
            pricelevel3: "0",
            pricelevel4: "0",
            pricelevel5: "0",
            pricelevel6: "0",
            pricelevel7: "72",
            pricelevel8: "0",
            pricelevel9: "0",
            product_type_unigram: "instructions",
            retailprice: "72",
            reviewaverage: "0",
            saleprice: "0",
            sku: "26500-002408",
            ss_aha_badge: "no",
            ss_clean_hierarchy: [
                "ALS~ALS Accessories~Physio-Control Manual Defibrillator Accessories",
                "allproductsexceptexcluded",
                "allproductsexceptexcludedNOAEDS",
                "ALS",
                "ALS~ALS Accessories~Physio-Control Manual Defibrillator Accessories~LIFEPAK 15 Accessories",
                "ALS~ALS Accessories~Physio-Control Manual Defibrillator Accessories~LIFEPAK 15 Accessories~Operating Instructions/Service Manuals/Videos",
                "ALS~ALS Accessories",
                "Discounted Accessories",
                "All Products excluding aha zoll accessories training manikins",
                "allproductsexceptexcluded-no-zoll",
            ],
            ss_name: "Physio-Control LIFEPAK 15 Monitor/Defibrillator Operating Instructions",
            stock: "4999",
            thumbnailImageUrl: "//www.aedsuperstore.com/assets/images/thumbnails/26500-002408_thumbnail.jpg",
            toplevelcategories:
                "Discounted  Accessories |ALS| All  Products  excluding  aha  zoll  accessories  training  manikins |allproductsexceptexcluded|allproductsexceptexcludedNOAEDS|allproductsexceptexcluded-no-zoll",
            uid: "1582",
            url: "https://www.aedsuperstore.com/physio-control-lifepak-15-monitor-defibrillator-operating-instructions.html",
        },
        {
            allcategories: [
                "Discounted  Accessories",
                "AED  Wall  Cabinets/Signs",
                "Signs,  Decals,  Posters",
                "AED  Wall  Signs",
                "Promotions",
                "Wall  Sign  Sale",
                "All  Products  excluding  aha  zoll  accessories  training  manikins",
                "allproductsexceptexcluded",
                "allproductsexceptexcludedNOAEDS",
                "allproductsexceptexcluded-no-zoll",
            ],
            brand: "Allied Medical Products",
            catalogid: "1798",
            categoryid: ["212", "319", "636", "1599", "1602", "1634", "1636"],
            categoryname: [
                "Discounted  Accessories",
                "AED  Wall  Signs",
                "Wall  Sign  Sale",
                "All  Products  excluding  aha  zoll  accessories  training  manikins",
                "allproductsexceptexcluded",
                "allproductsexceptexcludedNOAEDS",
                "allproductsexceptexcluded-no-zoll",
            ],
            categorypaths:
                "Discounted  Accessories | AED  Wall  Cabinets/Signs | AED  Wall  Cabinets/Signs  &gt;  Signs,  Decals,  Posters | AED  Wall  Cabinets/Signs  &gt;  Signs,  Decals,  Posters  &gt;  AED  Wall  Signs |Promotions| Promotions  &gt;  Wall  Sign  Sale | All  Products  excluding  aha  zoll  accessories  training  manikins |allproductsexceptexcluded|allproductsexceptexcludedNOAEDS|allproductsexceptexcluded-no-zoll",
            categoryspecial: "1",
            extrafield6: ["M3858A"],
            id: "d8ba483afeae08fb8d33e797de934022",
            imageUrl: "//www.aedsuperstore.com/assets/images/AMP3858-Side-one-T.jpg",
            intellisuggestData: "eJwASAC3_3pzcno0YQBmOWFhNjFlOC05MGYwLTRiNzQtYTE4NC04N2RhMzg0MThiNWIAZGVmaWIAQU1QMzg1OAAxADIAMAAyNTgAZ3JpZAMAygASQw",
            intellisuggestSignature: "45af6099416bc51e386aada2d96d0ee23e185eb276f753511af253b1b1c41fe8",
            msrp: "24.29",
            name: "Perpendicular Flange Mount Automated External Defibrillator Wall Sign",
            price: "29.19",
            pricelevel1: "29.19",
            pricelevel10: "0",
            pricelevel2: "0",
            pricelevel3: "0",
            pricelevel4: "0",
            pricelevel5: "0",
            pricelevel6: "0",
            pricelevel7: "29.19",
            pricelevel8: "0",
            pricelevel9: "0",
            product_type_unigram: "sign",
            retailprice: "24.29",
            reviewaverage: "1",
            saleprice: "0",
            sku: "AMP3858",
            ss_aha_badge: "no",
            ss_clean_hierarchy: [
                "allproductsexceptexcluded",
                "AED Wall Cabinets/Signs",
                "Promotions",
                "Promotions~Wall Sign Sale",
                "allproductsexceptexcludedNOAEDS",
                "AED Wall Cabinets/Signs~Signs, Decals, Posters~AED Wall Signs",
                "Discounted Accessories",
                "AED Wall Cabinets/Signs~Signs, Decals, Posters",
                "All Products excluding aha zoll accessories training manikins",
                "allproductsexceptexcluded-no-zoll",
            ],
            ss_name: "Perpendicular Flange Mount Automated External Defibrillator Wall Sign",
            stock: "6045",
            thumbnailImageUrl: "//www.aedsuperstore.com/assets/images/AMP3858-Side-one-T.jpg",
            toplevelcategories:
                "Discounted  Accessories | AED  Wall  Cabinets/Signs |Promotions| All  Products  excluding  aha  zoll  accessories  training  manikins |allproductsexceptexcluded|allproductsexceptexcludedNOAEDS|allproductsexceptexcluded-no-zoll",
            uid: "1798",
            url: "https://www.aedsuperstore.com/allied-medical-products-perpendicular-flange-mount-aed-wall-sign.html",
        },
        {
            allcategories: [
                "Discounted  Accessories",
                "Expiring  Parts  Landing  Pages",
                "HeartSine  PAD  AED  Replacement  Parts",
                "US  Club  Soccer",
                "Replacement  Pads",
                "All  Products  excluding  aha  zoll  accessories  training  manikins",
                "allproductsexceptexcluded",
                "allproductsexceptexcludedNOAEDS",
                "AED  Accessories",
                "HeartSine  Accessories",
                "samaritan  PAD  350P/360P  Accessories",
                "samaritan  PAD  450P  Accessories",
                "Heartsine  350/450  pads  and  batteries",
                "allproductsexceptexcluded-no-zoll",
            ],
            brand: "HeartSine",
            catalogid: "512",
            categoryid: ["212", "820", "1221", "1599", "1602", "1634", "228", "650", "1420", "1636"],
            categoryname: [
                "Discounted  Accessories",
                "HeartSine  PAD  AED  Replacement  Parts",
                "Replacement  Pads",
                "All  Products  excluding  aha  zoll  accessories  training  manikins",
                "allproductsexceptexcluded",
                "allproductsexceptexcludedNOAEDS",
                "samaritan  PAD  350P/360P  Accessories",
                "samaritan  PAD  450P  Accessories",
                "Heartsine  350/450  pads  and  batteries",
                "allproductsexceptexcluded-no-zoll",
            ],
            categorypaths:
                "Discounted  Accessories | Expiring  Parts  Landing  Pages | Expiring  Parts  Landing  Pages  &gt;  HeartSine  PAD  AED  Replacement  Parts | US  Club  Soccer | US  Club  Soccer  &gt;  Replacement  Pads | All  Products  excluding  aha  zoll  accessories  training  manikins |allproductsexceptexcluded|allproductsexceptexcludedNOAEDS| AED  Accessories | AED  Accessories  &gt;  HeartSine  Accessories | AED  Accessories  &gt;  HeartSine  Accessories  &gt;  samaritan  PAD  350P/360P  Accessories | AED  Accessories  &gt;  HeartSine  Accessories  &gt;  samaritan  PAD  450P  Accessories | AED  Accessories  &gt;  HeartSine  Accessories  &gt;  Heartsine  350/450  pads  and  batteries |allproductsexceptexcluded-no-zoll",
            categoryspecial: "1",
            extrafield6: ["PAD-PAK-01", "11516-000003", "300P", "350P", "PAD 300P", "PAD 300", "SAM 300P", "SAM 300", "360P", "450P", "PAD-PAK-03"],
            id: "5bf21a9f0bd067c14aa71b8909313609",
            imageUrl: "//www.aedsuperstore.com/assets/images/pad-pak-01-front-150x150.jpg",
            intellisuggestData: "eJwASwC0_3pzcno0YQBmOWFhNjFlOC05MGYwLTRiNzQtYTE4NC04N2RhMzg0MThiNWIAZGVmaWIAUEFELVBBSy0wMQAxADMAMAAyNTgAZ3JpZAMABNYS-g",
            intellisuggestSignature: "d07b49c401298c4f1fe26675d5e09b8ebf7dba2f4a49d13af2ee04750617ecad",
            msrp: "236",
            name: "HeartSine samaritan Pad-Pak",
            price: "236",
            pricelevel1: "236",
            pricelevel10: "0",
            pricelevel2: "0",
            pricelevel3: "0",
            pricelevel4: "0",
            pricelevel5: "0",
            pricelevel6: "0",
            pricelevel7: "236",
            pricelevel8: "0",
            pricelevel9: "0",
            product_type_unigram: "padpak",
            retailprice: "236",
            reviewaverage: "5",
            saleprice: "0",
            sku: "PAD-PAK-01",
            ss_aha_badge: "no",
            ss_clean_hierarchy: [
                "AED Accessories~HeartSine Accessories~samaritan PAD 350P/360P Accessories",
                "AED Accessories~HeartSine Accessories~samaritan PAD 450P Accessories",
                "Expiring Parts Landing Pages",
                "allproductsexceptexcludedNOAEDS",
                "AED Accessories~HeartSine Accessories~Heartsine 350/450 pads and batteries",
                "Discounted Accessories",
                "allproductsexceptexcluded-no-zoll",
                "allproductsexceptexcluded",
                "AED Accessories~HeartSine Accessories",
                "US Club Soccer~Replacement Pads",
                "Expiring Parts Landing Pages~HeartSine PAD AED Replacement Parts",
                "AED Accessories",
                "US Club Soccer",
                "All Products excluding aha zoll accessories training manikins",
            ],
            ss_name: "HeartSine samaritan Pad-Pak",
            stock: "88091",
            thumbnailImageUrl: "//www.aedsuperstore.com/assets/images/pad-pak-01-front-150x150.jpg",
            toplevelcategories:
                "Discounted  Accessories | Expiring  Parts  Landing  Pages | US  Club  Soccer | All  Products  excluding  aha  zoll  accessories  training  manikins |allproductsexceptexcluded|allproductsexceptexcludedNOAEDS| AED  Accessories |allproductsexceptexcluded-no-zoll",
            uid: "512",
            url: "https://www.aedsuperstore.com/heartsine-samaritan-pad-pak.html",
        },
        {
            allcategories: [
                "Discounted  Accessories",
                "AED  Accessories",
                "Defibtech  Accessories",
                "Lifeline  AED",
                "Expiring  Parts  Landing  Pages",
                "Defibtech  Lifeline  AED  Replacement  Parts",
                "US  Club  Soccer",
                "Pediatric  Pads",
                "All  Products  excluding  aha  zoll  accessories  training  manikins",
                "allproductsexceptexcluded",
                "allproductsexceptexcludedNOAEDS",
                "allproductsexceptexcluded-no-zoll",
                "approved  pads  batteries",
            ],
            brand: "Defibtech",
            catalogid: "338",
            categoryid: ["212", "392", "821", "1218", "172", "1599", "1602", "1634", "1636", "1639"],
            categoryname: [
                "Discounted  Accessories",
                "Lifeline  AED",
                "Defibtech  Lifeline  AED  Replacement  Parts",
                "Pediatric  Pads",
                "Defibtech  Accessories",
                "All  Products  excluding  aha  zoll  accessories  training  manikins",
                "allproductsexceptexcluded",
                "allproductsexceptexcludedNOAEDS",
                "allproductsexceptexcluded-no-zoll",
                "approved  pads  batteries",
            ],
            categorypaths:
                "Discounted  Accessories | AED  Accessories | AED  Accessories  &gt;  Defibtech  Accessories | AED  Accessories  &gt;  Defibtech  Accessories  &gt;  Lifeline  AED | Expiring  Parts  Landing  Pages | Expiring  Parts  Landing  Pages  &gt;  Defibtech  Lifeline  AED  Replacement  Parts | US  Club  Soccer | US  Club  Soccer  &gt;  Pediatric  Pads | All  Products  excluding  aha  zoll  accessories  training  manikins |allproductsexceptexcluded|allproductsexceptexcludedNOAEDS|allproductsexceptexcluded-no-zoll| approved  pads  batteries",
            categoryspecial: "1",
            id: "0be26e5b32ce06e3803203e8a9e9a40d",
            imageUrl: "//www.aedsuperstore.com/assets/images/ddp-200p-150x150.jpg",
            intellisuggestData: "eJwASQC2_3pzcno0YQBmOWFhNjFlOC05MGYwLTRiNzQtYTE4NC04N2RhMzg0MThiNWIAZGVmaWIARERQLTIwMFAAMQA0ADAAMjU4AGdyaWQDANw2EnY",
            intellisuggestSignature: "1481fd70f81a062ebbc2dd091bd544830eca32a50cf85f19ea696920552a91ae",
            msrp: "130.25",
            name: "Defibtech Lifeline or Lifeline AUTO AED Pediatric Defibrillation Electrode Pads - DDP-200P",
            price: "134.16",
            pricelevel1: "134.16",
            pricelevel10: "0",
            pricelevel2: "0",
            pricelevel3: "0",
            pricelevel4: "0",
            pricelevel5: "0",
            pricelevel6: "0",
            pricelevel7: "134.16",
            pricelevel8: "0",
            pricelevel9: "0",
            product_type_unigram: "pads",
            retailprice: "130.25",
            reviewaverage: "5",
            saleprice: "0",
            sku: "DDP-200P",
            ss_aha_badge: "no",
            ss_clean_hierarchy: [
                "AED Accessories~Defibtech Accessories~Lifeline AED",
                "Expiring Parts Landing Pages",
                "allproductsexceptexcludedNOAEDS",
                "Discounted Accessories",
                "allproductsexceptexcluded-no-zoll",
                "allproductsexceptexcluded",
                "Expiring Parts Landing Pages~Defibtech Lifeline AED Replacement Parts",
                "AED Accessories",
                "AED Accessories~Defibtech Accessories",
                "approved pads batteries",
                "US Club Soccer",
                "US Club Soccer~Pediatric Pads",
                "All Products excluding aha zoll accessories training manikins",
            ],
            ss_name: "Defibtech Lifeline or Lifeline AUTO AED Pediatric Defibrillation Electrode Pads",
            stock: "76470",
            thumbnailImageUrl: "//www.aedsuperstore.com/assets/images/ddp-200p-150x150.jpg",
            toplevelcategories:
                "Discounted  Accessories | AED  Accessories | Expiring  Parts  Landing  Pages | US  Club  Soccer | All  Products  excluding  aha  zoll  accessories  training  manikins |allproductsexceptexcluded|allproductsexceptexcludedNOAEDS|allproductsexceptexcluded-no-zoll| approved  pads  batteries",
            uid: "338",
            url: "https://www.aedsuperstore.com/defibtech-lifeline-aed-pediatric-defibrillation-electrode-pads.html",
        },
    ],
    facets: [
        {
            field: "ss_clean_hierarchy",
            label: "Category",
            type: "hierarchy",
            multiple: "single",
            collapse: 0,
            facet_active: 0,
            hierarchyDelimiter: "~",
            values: [
                {
                    active: false,
                    type: "value",
                    value: "All Products excluding aha zoll accessories training manikins",
                    label: "All Products excluding aha zoll accessories training manikins",
                    count: 189,
                },
                {
                    active: false,
                    type: "value",
                    value: "ALS",
                    label: "ALS",
                    count: 162,
                },
                {
                    active: false,
                    type: "value",
                    value: "Discounted Accessories",
                    label: "Discounted Accessories",
                    count: 155,
                },
                {
                    active: false,
                    type: "value",
                    value: "allproductsexceptexcluded",
                    label: "allproductsexceptexcluded",
                    count: 148,
                },
                {
                    active: false,
                    type: "value",
                    value: "allproductsexceptexcluded-no-zoll",
                    label: "allproductsexceptexcluded-no-zoll",
                    count: 144,
                },
                {
                    active: false,
                    type: "value",
                    value: "allproductsexceptexcludedNOAEDS",
                    label: "allproductsexceptexcludedNOAEDS",
                    count: 138,
                },
                {
                    active: false,
                    type: "value",
                    value: "AED Accessories",
                    label: "AED Accessories",
                    count: 43,
                },
                {
                    active: false,
                    type: "value",
                    value: "Promotions",
                    label: "Promotions",
                    count: 36,
                },
                {
                    active: false,
                    type: "value",
                    value: "Cabinets & Cases",
                    label: "Cabinets & Cases",
                    count: 29,
                },
                {
                    active: false,
                    type: "value",
                    value: "AED Wall Cabinets/Signs",
                    label: "AED Wall Cabinets/Signs",
                    count: 27,
                },
                {
                    active: false,
                    type: "value",
                    value: "AED Machines",
                    label: "AED Machines",
                    count: 19,
                },
                {
                    active: false,
                    type: "value",
                    value: "Facets",
                    label: "Facets",
                    count: 18,
                },
                {
                    active: false,
                    type: "value",
                    value: "US Club Soccer",
                    label: "US Club Soccer",
                    count: 17,
                },
                {
                    active: false,
                    type: "value",
                    value: "Training Products",
                    label: "Training Products",
                    count: 12,
                },
                {
                    active: false,
                    type: "value",
                    value: "Philips and Styrker AEDs and Packages",
                    label: "Philips and Styrker AEDs and Packages",
                    count: 11,
                },
                {
                    active: false,
                    type: "value",
                    value: "AED Total Cost of Ownership Calculator",
                    label: "AED Total Cost of Ownership Calculator",
                    count: 10,
                },
                {
                    active: false,
                    type: "value",
                    value: "allAEDSExceptExcluded",
                    label: "allAEDSExceptExcluded",
                    count: 10,
                },
                {
                    active: false,
                    type: "value",
                    value: "Expiring Parts Landing Pages",
                    label: "Expiring Parts Landing Pages",
                    count: 9,
                },
                {
                    active: false,
                    type: "value",
                    value: "AED Packages",
                    label: "AED Packages",
                    count: 7,
                },
                {
                    active: false,
                    type: "value",
                    value: "All ZOLL and Cardiac Science G5 AEDs and Packages",
                    label: "All ZOLL and Cardiac Science G5 AEDs and Packages",
                    count: 5,
                },
                {
                    active: false,
                    type: "value",
                    value: "Clearance",
                    label: "Clearance",
                    count: 5,
                },
                {
                    active: false,
                    type: "value",
                    value: "approved pads batteries",
                    label: "approved pads batteries",
                    count: 5,
                },
                {
                    active: false,
                    type: "value",
                    value: "End of Season Sale",
                    label: "End of Season Sale",
                    count: 4,
                },
                {
                    active: false,
                    type: "value",
                    value: "All Defibtech AEDs and Packages",
                    label: "All Defibtech AEDs and Packages",
                    count: 3,
                },
                {
                    active: false,
                    type: "value",
                    value: "Rescue Products",
                    label: "Rescue Products",
                    count: 3,
                },
                {
                    active: false,
                    type: "value",
                    value: "Klaviyo",
                    label: "Klaviyo",
                    count: 2,
                },
            ],
        },
        {
            field: "manufacturer",
            label: "Brand",
            type: "list",
            multiple: "multiple-union",
            collapse: 0,
            facet_active: 0,
            values: [
                {
                    active: false,
                    type: "value",
                    value: "Physio-Control",
                    label: "Physio-Control",
                    count: 92,
                },
                {
                    active: false,
                    type: "value",
                    value: "ZOLL Medical",
                    label: "ZOLL Medical",
                    count: 92,
                },
                {
                    active: false,
                    type: "value",
                    value: "Allied Medical Products",
                    label: "Allied Medical Products",
                    count: 27,
                },
                {
                    active: false,
                    type: "value",
                    value: "Defibtech",
                    label: "Defibtech",
                    count: 13,
                },
                {
                    active: false,
                    type: "value",
                    value: "HeartSine",
                    label: "HeartSine",
                    count: 7,
                },
                {
                    active: false,
                    type: "value",
                    value: "Philips Healthcare",
                    label: "Philips Healthcare",
                    count: 7,
                },
                {
                    active: false,
                    type: "value",
                    value: "Laerdal",
                    label: "Laerdal",
                    count: 5,
                },
                {
                    active: false,
                    type: "value",
                    value: "Allergy Emergency Kits",
                    label: "Allergy Emergency Kits",
                    count: 3,
                },
                {
                    active: false,
                    type: "value",
                    value: "Shok Box",
                    label: "Shok Box",
                    count: 3,
                },
                {
                    active: false,
                    type: "value",
                    value: "Simulaids",
                    label: "Simulaids",
                    count: 3,
                },
                {
                    active: false,
                    type: "value",
                    value: "Life/form",
                    label: "Life/form",
                    count: 2,
                },
                {
                    active: false,
                    type: "value",
                    value: "Nasco",
                    label: "Nasco",
                    count: 2,
                },
                {
                    active: false,
                    type: "value",
                    value: "Cardiac Science",
                    label: "Cardiac Science",
                    count: 1,
                },
            ],
        },
        {
            field: "ss_price",
            label: "Price",
            type: "list",
            multiple: "multiple-union",
            collapse: 0,
            facet_active: 0,
            values: [
                {
                    active: false,
                    type: "range",
                    low: "*",
                    high: "50",
                    label: "Less than $50",
                    count: 28,
                },
                {
                    active: false,
                    type: "range",
                    low: "50",
                    high: "100",
                    label: "$50 to $100",
                    count: 30,
                },
                {
                    active: false,
                    type: "range",
                    low: "100",
                    high: "250",
                    label: "$100 to $250",
                    count: 73,
                },
                {
                    active: false,
                    type: "range",
                    low: "250",
                    high: "500",
                    label: "$250 to $500",
                    count: 43,
                },
                {
                    active: false,
                    type: "range",
                    low: "500",
                    high: "1000",
                    label: "$500 to $1000",
                    count: 40,
                },
                {
                    active: false,
                    type: "range",
                    low: "1000",
                    high: "1500",
                    label: "$1000 to $1500",
                    count: 14,
                },
                {
                    active: false,
                    type: "range",
                    low: "1500",
                    high: "2500",
                    label: "$1500 to $2500",
                    count: 22,
                },
                {
                    active: false,
                    type: "range",
                    low: "2500",
                    high: "3500",
                    label: "$2500 to $3500",
                    count: 5,
                },
                {
                    active: false,
                    type: "range",
                    low: "3500",
                    high: "*",
                    label: "Over $3500",
                    count: 5,
                },
            ],
        },
        {
            field: "fully_automatic_option",
            label: "Fully-Automatic Option",
            type: "list",
            multiple: "multiple-union",
            collapse: 0,
            facet_active: 0,
            values: [
                {
                    active: false,
                    type: "value",
                    value: "No",
                    label: "No",
                    count: 7,
                },
                {
                    active: false,
                    type: "value",
                    value: "Yes",
                    label: "Yes",
                    count: 6,
                },
            ],
        },
        {
            field: "warranty",
            label: "Warranty",
            type: "list",
            multiple: "multiple-union",
            collapse: 0,
            facet_active: 0,
            values: [
                {
                    active: false,
                    type: "value",
                    value: "8 Years",
                    label: "8 Years",
                    count: 11,
                },
                {
                    active: false,
                    type: "value",
                    value: "5 Years",
                    label: "5 Years",
                    count: 1,
                },
                {
                    active: false,
                    type: "value",
                    value: "7 Years",
                    label: "7 Years",
                    count: 1,
                },
            ],
        },
        {
            field: "bilingual",
            label: "Bilingual",
            type: "list",
            multiple: "multiple-union",
            collapse: 0,
            facet_active: 0,
            values: [
                {
                    active: false,
                    type: "value",
                    value: "No",
                    label: "No",
                    count: 11,
                },
                {
                    active: false,
                    type: "value",
                    value: "Yes",
                    label: "Yes",
                    count: 1,
                },
            ],
        },
        {
            field: "remote_monitoring",
            label: "Remote Monitoring",
            type: "list",
            multiple: "multiple-union",
            collapse: 0,
            facet_active: 0,
            values: [
                {
                    active: false,
                    type: "value",
                    value: "No",
                    label: "No",
                    count: 12,
                },
            ],
        },
    ],
    breadcrumbs: [
        {
            field: "",
            label: 'Search: "defib"',
            filterLabel: "Search",
            filterValue: "defib",
            removeFilters: [],
            removeRefineQuery: [],
        },
    ],
    filterSummary: [],
    merchandising: {
        redirect: "",
        is_elevated: [],
        elevated: [],
        removed: [],
        content: {},
        facets: [],
        facetsHide: [],
        experiments: [],
        variants: [],
        personalized: false,
        triggeredCampaigns: [
            {
                id: "59957",
                title: "Global Campaign",
                type: "global",
            },
        ],
    },
    query: {
        matchType: "primary",
        subject: "defib",
    },
    features: {},
    responseId: "04eb84c34fbf28b5be4cf0d4b387c302d1cd1251faa1c87bdbcf887f5d948242",
};
